<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>page.php</string>
		<string>class.php</string>
		<string>func.php</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!.*php[0-9]{0,1}\b</string>
	<key>foldingStartMarker</key>
	<string>(/\*|\{\s*$|&lt;&lt;&lt;HTML)</string>
	<key>foldingStopMarker</key>
	<string>(\*/|^\s*\}|^HTML;)</string>
	<key>name</key>
	<string>Sandstone</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.php</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.php.sandstone</string>
	<key>uuid</key>
	<string>3E2DF57D-78BD-4CAD-B9B8-508F14E23E7B</string>
</dict>
</plist>
